name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"  # Gera a cada 12h
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar cobrinha personalizada
        uses: Platane/snk@v3
        with:
          github_user_name: matheus-fernandes-dev
          outputs: dist/github-contribution-grid-snake.svg
          palette: "#6f42c1 #58a6ff #2f81f7" # Roxo e Azul personalizados

      - name: Commit e push da cobrinha
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: actions@github.com
          message: "Atualizando cobrinha personalizada"
          add: "dist/github-contribution-grid-snake.svg"

      - name: Deploy cobrinha no branch output
        run: |
          git fetch
          git checkout output || git checkout --orphan output
          git reset
          mv dist/github-contribution-grid-snake.svg .
          git add github-contribution-grid-snake.svg
          git commit -m "Atualizando cobrinha personalizada"
          git push origin output --force
