name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Executa todo dia à meia-noite UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      # Baixa o repositório
      - name: Checkout
        uses: actions/checkout@v3

      # Gera a cobrinha personalizada
      - name: Generate snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: matheus-fernandes-dev
          outputs: dist/github-contribution-grid-snake.svg
          color_snake: "#6f42c1"
          color_dots: "#58a6ff,#2f81f7,#6f42c1,#ffffff"

      # Publica no branch output
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
